CREATE TABLE CK_BOARD(
	SEQ NUMBER PRIMARY KEY,
	CONTENT CLOB
);

SELECT NVL(MAX(SEQ),0)+1
	FROM CK_BOARD;

INSERT INTO HR.CK_BOARD(SEQ, CONTENT)
		VALUES((SELECT NVL(MAX(SEQ),0)+1 FROM CK_BOARD), 'content');

SELECT SEQ, LENGTH(CONTENT)
	FROM CK_BOARD cb 
	ORDER BY 1;